apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
