apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wwwplotnikov/gitops-demo-config.git
    targetRevision: main
    path: charts/demoapp

  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
